# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminCourseManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(906, 691)
        self.deleteCourseButton = QtWidgets.QPushButton(Dialog)
        self.deleteCourseButton.setGeometry(QtCore.QRect(410, 610, 101, 51))
        self.deleteCourseButton.setObjectName("deleteCourseButton")
        self.uploadCourseButton = QtWidgets.QPushButton(Dialog)
        self.uploadCourseButton.setGeometry(QtCore.QRect(740, 40, 101, 41))
        self.uploadCourseButton.setObjectName("uploadCourseButton")
        self.deleteCourseStuButton = QtWidgets.QPushButton(Dialog)
        self.deleteCourseStuButton.setGeometry(QtCore.QRect(530, 610, 141, 51))
        self.deleteCourseStuButton.setObjectName("deleteCourseStuButton")
        self.deleteCourseteacherButton = QtWidgets.QPushButton(Dialog)
        self.deleteCourseteacherButton.setGeometry(QtCore.QRect(690, 610, 141, 51))
        self.deleteCourseteacherButton.setObjectName("deleteCourseteacherButton")
        self.courseListLabel = QtWidgets.QTableView(Dialog)
        self.courseListLabel.setGeometry(QtCore.QRect(80, 120, 761, 461))
        self.courseListLabel.setStyleSheet("background-color: rgb(104, 168, 231);")
        self.courseListLabel.setObjectName("courseListLabel")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(80, 40, 611, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.adminSearchCourse = QtWidgets.QLineEdit(self.widget)
        self.adminSearchCourse.setObjectName("adminSearchCourse")
        self.horizontalLayout.addWidget(self.adminSearchCourse)
        self.courseSearchButton = QtWidgets.QPushButton(self.widget)
        self.courseSearchButton.setObjectName("courseSearchButton")
        self.horizontalLayout.addWidget(self.courseSearchButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.deleteCourseButton.setText(_translate("Dialog", "删除指定课程"))
        self.uploadCourseButton.setText(_translate("Dialog", "导入课程信息"))
        self.deleteCourseStuButton.setText(_translate("Dialog", "修改课程可选学生"))
        self.deleteCourseteacherButton.setText(_translate("Dialog", "修改课程任课老师"))
        self.courseSearchButton.setText(_translate("Dialog", "搜索课程"))
