# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminCourseManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(906, 691)
        Dialog.setMinimumSize(QtCore.QSize(906, 691))
        Dialog.setMaximumSize(QtCore.QSize(906, 691))
        self.showSearchSubsResult = QtWidgets.QTableWidget(Dialog)
        self.showSearchSubsResult.setGeometry(QtCore.QRect(10, 100, 891, 511))
        self.showSearchSubsResult.setStyleSheet("")
        self.showSearchSubsResult.setObjectName("showSearchSubsResult")
        self.showSearchSubsResult.setColumnCount(0)
        self.showSearchSubsResult.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 40, 611, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.adminSearchCourse = QtWidgets.QLineEdit(self.layoutWidget)
        self.adminSearchCourse.setObjectName("adminSearchCourse")
        self.horizontalLayout.addWidget(self.adminSearchCourse)
        self.courseSearchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.courseSearchButton.setObjectName("courseSearchButton")
        self.horizontalLayout.addWidget(self.courseSearchButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.courseSearchButton.setText(_translate("Dialog", "搜索课程"))
