# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminCollegeManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 692)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.addCollegeButton = QtWidgets.QPushButton(Dialog)
        self.addCollegeButton.setGeometry(QtCore.QRect(150, 200, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addCollegeButton.setFont(font)
        self.addCollegeButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                            "color: rgb(255, 255, 255);")
        self.addCollegeButton.setObjectName("addCollegeButton")
        self.addMajorButton = QtWidgets.QPushButton(Dialog)
        self.addMajorButton.setGeometry(QtCore.QRect(320, 200, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addMajorButton.setFont(font)
        self.addMajorButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                          "color: rgb(255, 255, 255);")
        self.addMajorButton.setObjectName("addMajorButton")
        self.delMajorButton = QtWidgets.QPushButton(Dialog)
        self.delMajorButton.setGeometry(QtCore.QRect(320, 370, 150, 150))
        self.delMajorButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                          "color: rgb(255, 255, 255);")
        self.delMajorButton.setObjectName("delMajorButton")
        self.delCollegeButton = QtWidgets.QPushButton(Dialog)
        self.delCollegeButton.setGeometry(QtCore.QRect(150, 370, 150, 150))
        self.delCollegeButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                            "color: rgb(255, 255, 255);")
        self.delCollegeButton.setObjectName("delCollegeButton")
        self.addTrainProgramButton = QtWidgets.QPushButton(Dialog)
        self.addTrainProgramButton.setGeometry(QtCore.QRect(500, 200, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addTrainProgramButton.setFont(font)
        self.addTrainProgramButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                                 "color: rgb(255, 255, 255);")
        self.addTrainProgramButton.setObjectName("addTrainProgramButton")
        self.delTrainProgramButton = QtWidgets.QPushButton(Dialog)
        self.delTrainProgramButton.setGeometry(QtCore.QRect(500, 370, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.delTrainProgramButton.setFont(font)
        self.delTrainProgramButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                                 "color: rgb(255, 255, 255);")
        self.delTrainProgramButton.setObjectName("delTrainProgramButton")
        self.collegeTextlabel = QtWidgets.QLabel(Dialog)
        self.collegeTextlabel.setGeometry(QtCore.QRect(350, 100, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.collegeTextlabel.setFont(font)
        self.collegeTextlabel.setObjectName("collegeTextlabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addCollegeButton.setText(_translate("Dialog", "添加学院"))
        self.addMajorButton.setText(_translate("Dialog", "添加专业"))
        self.delMajorButton.setText(_translate("Dialog", "删除专业"))
        self.delCollegeButton.setText(_translate("Dialog", "删除学院"))
        self.addTrainProgramButton.setText(_translate("Dialog", "添加培养方案"))
        self.delTrainProgramButton.setText(_translate("Dialog", "删除培养方案"))
        self.collegeTextlabel.setText(_translate("Dialog", "学院管理"))
