# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminCollegeManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 692)
        Dialog.setMinimumSize(QtCore.QSize(792, 692))
        Dialog.setMaximumSize(QtCore.QSize(792, 720))
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.collegeTextlabel = QtWidgets.QLabel(Dialog)
        self.collegeTextlabel.setGeometry(QtCore.QRect(350, 0, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.collegeTextlabel.setFont(font)
        self.collegeTextlabel.setObjectName("collegeTextlabel")
        self.showCollegeResult = QtWidgets.QTreeWidget(Dialog)
        self.showCollegeResult.setGeometry(QtCore.QRect(25, 81, 741, 591))
        self.showCollegeResult.setObjectName("showCollegeResult")
        self.showCollegeResult.headerItem().setText(0, "1")
        self.uploadAllButton = QtWidgets.QPushButton(Dialog)
        self.uploadAllButton.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.uploadAllButton.setObjectName("uploadAllButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.collegeTextlabel.setText(_translate("Dialog", "学院管理"))
        self.uploadAllButton.setText(_translate("Dialog", "导入学院专业"))
