# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 544)
        MainWindow.setMinimumSize(QtCore.QSize(644, 544))
        MainWindow.setMaximumSize(QtCore.QSize(644, 544))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(80, -10, 501, 341))
        self.listView.setMinimumSize(QtCore.QSize(501, 341))
        self.listView.setMaximumSize(QtCore.QSize(501, 341))
        self.listView.setStyleSheet("background-image: url(:/login/jxufe.jpg);")
        self.listView.setObjectName("listView")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(266, 466, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.loginPasswdPrompt = QtWidgets.QLabel(self.centralwidget)
        self.loginPasswdPrompt.setGeometry(QtCore.QRect(197, 410, 77, 16))
        self.loginPasswdPrompt.setObjectName("loginPasswdPrompt")
        self.loginPasswdInput = QtWidgets.QLineEdit(self.centralwidget)
        self.loginPasswdInput.setGeometry(QtCore.QRect(280, 410, 171, 21))
        self.loginPasswdInput.setObjectName("loginPasswdInput")
        self.loginNamePrompt = QtWidgets.QLabel(self.centralwidget)
        self.loginNamePrompt.setGeometry(QtCore.QRect(197, 360, 77, 16))
        self.loginNamePrompt.setObjectName("loginNamePrompt")
        self.loginNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.loginNameInput.setGeometry(QtCore.QRect(280, 360, 171, 21))
        self.loginNameInput.setObjectName("loginNameInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButton.setText(_translate("MainWindow", "登录"))
        self.loginPasswdPrompt.setText(_translate("MainWindow", "密码：    "))
        self.loginNamePrompt.setText(_translate("MainWindow", "账号：    "))
import res.res_rc