# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectedSubsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(774, 635)
        Dialog.setMinimumSize(QtCore.QSize(774, 635))
        Dialog.setMaximumSize(QtCore.QSize(774, 635))
        self.showSelectedSubs = QtWidgets.QTableWidget(Dialog)
        self.showSelectedSubs.setGeometry(QtCore.QRect(5, 51, 761, 571))
        self.showSelectedSubs.setMinimumSize(QtCore.QSize(761, 571))
        self.showSelectedSubs.setMaximumSize(QtCore.QSize(761, 571))
        self.showSelectedSubs.setObjectName("showSelectedSubs")
        self.showSelectedSubs.setColumnCount(0)
        self.showSelectedSubs.setRowCount(0)
        self.topPrompt = QtWidgets.QLabel(Dialog)
        self.topPrompt.setGeometry(QtCore.QRect(370, 20, 72, 15))
        self.topPrompt.setObjectName("topPrompt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.topPrompt.setText(_translate("Dialog", "已选课程"))
