# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stuHome.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(751, 596)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 50, 721, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selfInformButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selfInformButton.setObjectName("selfInformButton")
        self.horizontalLayout.addWidget(self.selfInformButton)
        self.selectedButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selectedButton.setObjectName("selectedButton")
        self.horizontalLayout.addWidget(self.selectedButton)
        self.logOutButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.logOutButton.setObjectName("logOutButton")
        self.horizontalLayout.addWidget(self.logOutButton)
        self.stuHomeTitleLabel = QtWidgets.QLabel(Dialog)
        self.stuHomeTitleLabel.setGeometry(QtCore.QRect(340, 0, 101, 41))
        self.stuHomeTitleLabel.setObjectName("stuHomeTitleLabel")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(19, 109, 721, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchSubsInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.searchSubsInput.setObjectName("searchSubsInput")
        self.horizontalLayout_2.addWidget(self.searchSubsInput)
        self.searchSubsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.searchSubsButton.setObjectName("searchSubsButton")
        self.horizontalLayout_2.addWidget(self.searchSubsButton)
        self.showSearchResult = QtWidgets.QTableWidget(Dialog)
        self.showSearchResult.setGeometry(QtCore.QRect(25, 161, 711, 431))
        self.showSearchResult.setMinimumSize(QtCore.QSize(711, 431))
        self.showSearchResult.setMaximumSize(QtCore.QSize(711, 431))
        self.showSearchResult.setObjectName("showSearchResult")
        self.showSearchResult.setColumnCount(0)
        self.showSearchResult.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selfInformButton.setText(_translate("Dialog", "个人信息"))
        self.selectedButton.setText(_translate("Dialog", "已选课程"))
        self.logOutButton.setText(_translate("Dialog", "登出"))
        self.stuHomeTitleLabel.setText(_translate("Dialog", "学生选课系统"))
        self.searchSubsButton.setText(_translate("Dialog", "搜索课程"))
