# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherFeedback.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 585)
        self.feedbackLabel = QtWidgets.QLabel(Dialog)
        self.feedbackLabel.setGeometry(QtCore.QRect(300, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.feedbackLabel.setFont(font)
        self.feedbackLabel.setObjectName("feedbackLabel")
        self.messageLabel = QtWidgets.QLabel(Dialog)
        self.messageLabel.setGeometry(QtCore.QRect(40, 250, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.messageLabel.setFont(font)
        self.messageLabel.setObjectName("messageLabel")
        self.messageTextEdit = QtWidgets.QTextEdit(Dialog)
        self.messageTextEdit.setGeometry(QtCore.QRect(130, 140, 431, 281))
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.submitButton = QtWidgets.QPushButton(Dialog)
        self.submitButton.setGeometry(QtCore.QRect(280, 450, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.feedbackLabel.setText(_translate("Dialog", "反馈"))
        self.messageLabel.setText(_translate("Dialog", "留言："))
        self.messageTextEdit.setHtml(_translate("Dialog",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入反馈内容</p></body></html>"))
        self.submitButton.setText(_translate("Dialog", "提交"))
