# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userInformWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(603, 501)
        Dialog.setMinimumSize(QtCore.QSize(603, 501))
        Dialog.setMaximumSize(QtCore.QSize(603, 501))
        self.showSelfInform = QtWidgets.QLabel(Dialog)
        self.showSelfInform.setGeometry(QtCore.QRect(31, 54, 541, 421))
        self.showSelfInform.setText("")
        self.showSelfInform.setObjectName("showSelfInform")
        self.topPrompt = QtWidgets.QLabel(Dialog)
        self.topPrompt.setGeometry(QtCore.QRect(270, 10, 72, 15))
        self.topPrompt.setObjectName("topPrompt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.topPrompt.setText(_translate("Dialog", "个人信息"))
